Repository abundis28/mintern, pull requests merged in 2020-08, with the labels that each got.

#17 Adds utility class to avoid repetition of method declarations across …
  src/main/java/com/google/sps/classes/Utility.java
Labels: enhancement

#14 Add test app for running queries from a Java servlet
  tests/java-db-test/README.md
  tests/java-db-test/mysql/create.sql
  tests/java-db-test/mysql/populate.sql
  tests/java-db-test/pom.xml
  tests/java-db-test/src/main/java/testing/servlets/TestServlet.java
  tests/java-db-test/src/main/webapp/WEB-INF/appengine-web.xml
  tests/java-db-test/src/main/webapp/index.html
  tests/java-db-test/src/main/webapp/script.js
Labels: documentation

#12 Add file to create the database
  src/mysql/create.sql
  src/mysql/populate.sql
Labels: MVP

#26 Add authors of questions and answers to be followers their posts
  src/mysql/populate.sql
Labels: hotfix

#38 Fix Utility class
  src/main/java/com/google/sps/classes/Utility.java
Labels: hotfix

#37 Hotfix to sql database to test emails.
  src/mysql/populate.sql
Labels: hotfix

#42 Hotfix/utility sql variables
  src/main/java/com/google/sps/classes/Utility.java
Labels: hotfix

#20 Mvp/fetch posts
  src/main/java/com/google/sps/classes/QuestionObject.java
  src/main/java/com/google/sps/servlets/FetchForumServlet.java
  src/main/webapp/index.html
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: MVP

#57 Fix variable names
  src/main/java/com/google/sps/servlets/FetchForumServlet.java
  src/main/java/com/google/sps/servlets/MentorSignupServlet.java
Labels: hotfix

#58 Delete an unused servlet file
  src/main/java/com/google/sps/servlets/DataServlet.java
Labels: hotfix

#59 Fix other variables
  src/main/java/com/google/sps/classes/Utility.java
Labels: hotfix

#32 Mvp/post questions
  src/main/java/com/google/sps/classes/SqlConstants.java
  src/main/java/com/google/sps/classes/Utility.java
  src/main/java/com/google/sps/servlets/FetchForumServlet.java
  src/main/java/com/google/sps/servlets/PostQuestionServlet.java
  src/main/webapp/index.html
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: MVP

#54 Mvp/notifications (Questions and Answers)
  src/main/java/com/google/sps/classes/Notification.java
  src/main/java/com/google/sps/classes/SqlConstants.java
  src/main/java/com/google/sps/classes/Utility.java
  src/main/java/com/google/sps/servlets/FetchForumServlet.java
  src/main/java/com/google/sps/servlets/NotificationServlet.java
  src/main/webapp/index.html
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: MVP

#74 Alpha/build question function
  src/main/java/com/google/sps/classes/Utility.java
  src/main/java/com/google/sps/servlets/FetchForumServlet.java
Labels: alpha

#87 Reorder functions
  src/main/webapp/script.js
Labels: hotfix

#82 Mvp/show answers
  src/main/java/com/google/sps/classes/Answer.java
  src/main/java/com/google/sps/classes/Comment.java
  src/main/java/com/google/sps/classes/Question.java
  src/main/java/com/google/sps/classes/SqlConstants.java
  src/main/java/com/google/sps/classes/Utility.java
  src/main/java/com/google/sps/servlets/FetchAnswersServlet.java
  src/main/java/com/google/sps/servlets/FetchQuestionsServlet.java
  src/main/webapp/question.html
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: MVP

#91 Fixes double call of fetchNotifications().
  src/main/webapp/script.js
Labels: hotfix

#96 Single question view hotfix
  src/main/webapp/question.html
Labels: hotfix

#90 Alpha/question search
  src/main/java/com/google/sps/classes/SqlConstants.java
  src/main/java/com/google/sps/servlets/QuestionSearchServlet.java
  src/main/webapp/index.html
  src/main/webapp/script.js
  src/main/webapp/style.css
  src/mysql/create.sql
Labels: alpha

#93 Alpha/notifications answer url correction
  src/main/java/com/google/sps/classes/SqlConstants.java
  src/main/java/com/google/sps/servlets/NotificationServlet.java
Labels: bug

#105 Hotfix/fetch function
  src/main/webapp/script.js
Labels: hotfix

#99 Mvp/notify users from posts
  src/main/java/com/google/sps/servlets/PostAnswerServlet.java
  src/main/java/com/google/sps/servlets/PostCommentServlet.java
Labels: MVP

#107 Add missing TODO
  src/main/java/com/google/sps/servlets/PostCommentServlet.java
Labels: hotfix

#106 Add notification inbox to question page
  src/main/webapp/index.html
  src/main/webapp/question.html
Labels: MVP

#98 Hide forms and show them when the user is logged in
  src/main/webapp/index.html
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: MVP

#108 Alpha/question search
  src/main/webapp/index.html
  src/main/webapp/question.html
  src/main/webapp/script.js
Labels: bug

#136 Changes to pom.xml
  pom.xml
Labels: hotfix

#115 Front end for the follower system
  src/main/java/com/google/sps/classes/Question.java
  src/main/java/com/google/sps/classes/SqlConstants.java
  src/main/java/com/google/sps/classes/Utility.java
  src/main/java/com/google/sps/servlets/FetchQuestionsServlet.java
  src/main/webapp/index.html
  src/main/webapp/script.js
Labels: alpha

#118 Follower system backend
  src/main/java/com/google/sps/classes/SqlConstants.java
  src/main/java/com/google/sps/servlets/FollowerSystemServlet.java
  src/main/webapp/question.html
  src/main/webapp/script.js
Labels: alpha

#138 Add restraint for required fields
  src/main/webapp/index.html
  src/main/webapp/question.html
  src/main/webapp/script.js
Labels: alpha

#140 merge already approved changes
  src/main/java/com/google/sps/classes/SqlConstants.java
  src/main/java/com/google/sps/servlets/FollowerSystemServlet.java
  src/main/webapp/question.html
  src/main/webapp/script.js
Labels: hotfix

#142 Fixes prepared statement.
  src/main/java/com/google/sps/servlets/QuestionSearchServlet.java
Labels: hotfix

#143 Changes color of search button.
  src/main/webapp/index.html
  src/main/webapp/question.html
Labels: hotfix

#135 Alpha/limit forum posts
  src/main/java/com/google/sps/classes/ForumPage.java
  src/main/java/com/google/sps/classes/SqlConstants.java
  src/main/java/com/google/sps/classes/Utility.java
  src/main/java/com/google/sps/servlets/FetchQuestionsServlet.java
  src/main/java/com/google/sps/servlets/QuestionSearchServlet.java
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: alpha

#141 Final/verified mentor check
  src/main/java/com/google/sps/classes/Answer.java
  src/main/java/com/google/sps/classes/Comment.java
  src/main/java/com/google/sps/classes/SqlConstants.java
  src/main/java/com/google/sps/servlets/FetchAnswersServlet.java
  src/main/webapp/script.js
Labels: final

#144 Final/refactor
  src/main/java/com/google/sps/classes/Utility.java
  src/main/java/com/google/sps/servlets/AnswerServlet.java
  src/main/java/com/google/sps/servlets/FetchQuestionsServlet.java
  src/main/java/com/google/sps/servlets/PostAnswerServlet.java
  src/main/java/com/google/sps/servlets/PostCommentServlet.java
  src/main/java/com/google/sps/servlets/QuestionServlet.java
  src/main/webapp/approval.html
  src/main/webapp/index.html
  src/main/webapp/question.html
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: final

#148 Fix variable naming and function execution
  src/main/webapp/script.js
Labels: hotfix

#123 Bug/access cloud sql
  pom.xml
  src/main/java/com/google/sps/classes/HikariConstants.java
  src/main/java/com/google/sps/classes/Utility.java
  src/main/java/com/google/sps/listeners/ConnectionPoolContextListener.java
  src/main/java/com/google/sps/servlets/AnswerServlet.java
  src/main/java/com/google/sps/servlets/AuthenticationServlet.java
  src/main/java/com/google/sps/servlets/FollowerSystemServlet.java
  src/main/java/com/google/sps/servlets/MentorApprovalServlet.java
  src/main/java/com/google/sps/servlets/MentorEvidenceServlet.java
  src/main/java/com/google/sps/servlets/NotificationServlet.java
  src/main/java/com/google/sps/servlets/PostCommentServlet.java
  src/main/java/com/google/sps/servlets/QuestionSearchServlet.java
  src/main/java/com/google/sps/servlets/QuestionServlet.java
  src/main/java/com/google/sps/servlets/SignupMenteeServlet.java
  src/main/java/com/google/sps/servlets/SignupMentorServlet.java
  src/main/java/com/google/sps/servlets/SignupServlet.java
  src/main/webapp/script.js
  tests/java-db-test/src/main/java/testing/servlets/TestServlet.java
Labels: bug

#139 Bug/conceal sql keys class
  .gitignore
  src/main/java/com/google/sps/classes/Utility.java
  src/main/java/com/google/sps/listeners/ConnectionPoolContextListener.java
Labels: bug

#151 Hotfix/missing changes
  src/main/java/com/google/sps/classes/HikariConstants.java
  src/main/webapp/script.js
Labels: hotfix

#152 Erases console.
  src/main/webapp/script.js
Labels: hotfix

#153 Erases function that is not used.
  src/main/webapp/script.js
Labels: hotfix

#36 Mvp/emails
  pom.xml
  src/main/java/com/google/sps/classes/Utility.java
  src/main/java/com/google/sps/servlets/AnswerServlet.java
  src/main/java/com/google/sps/servlets/EmailServlet.java
  src/main/java/com/google/sps/servlets/FollowerSystemServlet.java
  src/main/java/com/google/sps/servlets/NotificationServlet.java
  src/main/java/com/google/sps/servlets/PostCommentServlet.java
  src/main/java/com/google/sps/servlets/QuestionServlet.java
Labels: MVP

#155 Hotfix/email servlet call
  src/main/java/com/google/sps/servlets/NotificationServlet.java
Labels: hotfix

#145 Final/notifications badge
  src/main/webapp/index.html
  src/main/webapp/question.html
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: final

#150 Final/hide follower buttons
  src/main/webapp/script.js
Labels: final

#156 Fix test DB values
  src/mysql/testPopulate.sql
  tests/java-db-test/mysql/create.sql
  tests/java-db-test/mysql/testPopulate.sql
Labels: hotfix

#159 Add favicon
  src/main/webapp/favicon.ico
Labels: final

#160 Hotfix/notification dropdown question html
  src/main/webapp/question.html
Labels: hotfix

#161 Hotfix/change var
  src/main/webapp/script.js
Labels: hotfix

#164 Tests/email string
  src/main/java/com/google/sps/classes/Utility.java
  src/test/java/com/google/sps/UtilityTest.java
Labels: test

#172 Test/email servlet utility methods
  pom.xml
  src/test/java/com/google/sps/UtilityTest.java
Labels: test

#168 Tests/build question
  src/test/java/com/google/sps/UtilityTest.java
Labels: test

#165 Tests/split pages
  src/main/java/com/google/sps/classes/Utility.java
  src/test/java/com/google/sps/UtilityTest.java
Labels: test

#173 Adds test for buildAnswer() with JSON.
  src/test/java/com/google/sps/UtilityTest.java
Labels: test
